### ISSUE TITLE
After logging in, no server is selected

### ISSUE THREAD

**Issue by pitkley** [XereoNet/SpaceBukkitPanel#1]
When I log into the SpaceBukkit panel I get an error message of the server being down, the reason being that no server is selected, although I have two servers installed. It would be nice if the panel either selected just the first server in the list or even saves the last selected server in a cookie.

I am running open beta 1.1, upgraded from 1.0 with the install.sh-script. This issue also existed in 1.0.

**Comment by pitkley** [comment]
Okay, I just found the account settings in which you can set the favourite server. Now it works flawless.

Keep up the good work guys!

**Comment by Antariano** [comment]
Yes, favourite server was bugged, is fixed in 1.1 :)

**Comment by pitkley** [comment]
Ah, I see. Thanks for the response!
