### ISSUE TITLE
New Instalation System does not Work

### ISSUE THREAD

**Issue by lucasdidur** [XereoNet/SpaceBukkitPanel#10]
I'm trying to do a clean install with the latest version available, but not installing it.

I go to step 5, and says that it installed, but it always comes back to the first page of the installation.

Another error:

The app / config / database file is NOT writable.

This file is writable yes, and he set up the installation.

**Comment by EnZiGuRi** [comment]
The app / config / database file is NOT writable.

i changed this file to the old one and it worked, i think it is empty.

about the step 5... same for me but i dont go to the first page, i just press the button and dont work.

**Comment by Antariano** [comment]
Please don't use the github version. It's a WIP 1.2 version that indeed does not work, I deactivated the installer in it. Sorry about that. Please use http://forums.xereo.net/threads/spacebukkit-1-1-released.131/

**Comment by Antariano** [comment]
Reason being I was still new to git and didn't use branches. Won't happen again once 1.2 is done :)
