### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by Magi1053** [XereoNet/SpaceBukkitPanel#12]
So i put the files inside a folder of my web host called webserver, so i can access it from http://localhost/webserver/ and this is the error i get:

Error: 400 - The requested address '/WebServer/webserver/' was not found on this server.

**Comment by Rockstar04** [comment]
Do you have the proper mod-rewrite enabled?

**Comment by Magi1053** [comment]
I have tried it on another host not on the same network as mine, using the exact same webserver as me, and it works on there.
