### ISSUE TITLE
TuserController not found

### ISSUE THREAD

**Issue by Bootscreen** [XereoNet/SpaceBukkitPanel#3]
hy,

this is a repost from here: https://github.com/SpaceDev/SpaceBukkit/issues/134 because PitBull2709 informed me that this should be the right place.

when i shutdown my server and try to open the user-page i get the following error:
http://img703.imageshack.us/img703/6167/tusercontrollererror.png

The Problem is, when i shutdown the server in the top menü stands benutzer / user with a link to tusers (http://img714.imageshack.us/img714/8184/overviewtusers.png)
but when i start the server there is a point with spieler / players and a link to tplayers.

And PitBull2709 has the same Problem, he post it in the old IssueThread

**Comment by Antariano** [comment]
Thanks to PitBull2709 and his latest pull request
SpaceDev/SpaceBukkitPanel@9e31bd3bc8f716ed8ef43317c5cdc6df6e9378bc
this is now fixed, it was some old code floating around :)
